version: '3.8'

services:
  backend:
    build: .
    restart: unless-stopped
    ports:
      - "5000:5000"
    depends_on:
      - mongo
    environment:
      - PORT=5000
      - MONGODB_URI=mongodb://mongo:27017/drawwave
      - NODE_ENV=development
      - SESSION_SECRET=drawwave_secret
    volumes:
      - ./:/app
      - /app/node_modules

  mongo:
    image: mongo:latest
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
