version: '3.8'

services:
  drawwave-python:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: drawwave-python
    ports:
      - "8765:8765"
    volumes:
      # Mount the code directory for development
      - .:/app
    restart: unless-stopped
    networks:
      - drawwave-network
      - backend-network
    environment:
      - API_URL=http://backend:5000/api  # Connect to backend by service name

networks:
  drawwave-network:
    driver: bridge
  backend-network:
    external: true
    name: backend_default  # This should match the network name created by the backend docker-compose
